### ISSUE TITLE
Youtube Upload button is not working using this

### ISSUE THREAD

**Issue by yazhamuthan-aruchamy** [clicknium/clicknium-docs#58] opened 2023-04-17 01:24 UTC
I have tried to automate the YouTube using clicknium but I am not able to click on the upload button i tired multiple times but not working as expected. also, every time it was saying the clicknium started to be debugging the browser but in the video that was not showing anything I have tried with this also no proper documentation and no customer support properly please someone help me with this. 
Attached the code for reference :

```
from clicknium import clicknium as cc,locator,ui
from time import sleep

tab = cc.chrome.open("https://www.youtube.com")
sleep(8)
cc.find_element(locator.youtube.yt_icon_button_button).click(mouse_button = "left") #tried with just click() also
print("done 1")
sleep(5)
print("DOne 3")
cc.find_element(locator.youtube.link_style_scope_ytd_compact_link_renderer).click(mouse_button = "left")
print("done 2")
sleep(5)
tab.close()
```

If anyone was aware of this, please tell us or if there is any mistake in this code, please let us know

**Comment by kayYOLO** [comment] 2023-04-19 06:09
As we As we discussed in the meeting, this issue was caused by screen zoom ratio. The workaround is that change the zoom ratio back to 100%. This issue should be fixed in the next release.

**Comment by DragonLi-Mi** [comment] 2023-06-03 07:57
fixed

**Closed by DragonLi-Mi** 2023-06-03 07:57 UTC
